#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: Merge-upstream

on:
  #11/18/2021
  push:
    branches: 
      - master
  #schedule:
  #  - cron: 30 19 * * *

jobs:
  merge:

    runs-on: ubuntu-20.04

    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: master
        fetch-depth: 0
        lfs: true

    - name: Set git identity
      run : |
        git config --global user.email "gotaduckyy@protonmail.com"
        git config --global user.name "Lenoix"
    - name: Load upstream commits
      run: git pull https://github.com/hanwckf/rt-n56u.git --no-edit --strategy-option ours

    - name: Push Commits
      env:
        DOWNSTREAM_BRANCH: master
      run: git push origin $DOWNSTREAM_BRANCH
